#!/usr/bin/env bash
#
# AuditCore — Production installer (On-Premise Smart Box).
# Target: fresh Ubuntu 22.04, < 30 min from start to login page.
#
# Current architecture: app/worker/redis/baileys run on the box; PostgreSQL +
# Auth are provided by Supabase (see .env). To run a fully self-contained box
# with a LOCAL postgres, see DEPLOYMENT.md ("Fully on-prem Postgres").
#
set -euo pipefail

bold()  { printf "\033[1m%s\033[0m\n" "$*"; }
green() { printf "\033[32m%s\033[0m\n" "$*"; }
yellow(){ printf "\033[33m%s\033[0m\n" "$*"; }
red()   { printf "\033[31m%s\033[0m\n" "$*"; }
fail()  { red "✗ $*"; exit 1; }

gen_secret() { openssl rand -hex 32 2>/dev/null || head -c32 /dev/urandom | od -An -tx1 | tr -d ' \n'; }
gen_password() { openssl rand -base64 18 2>/dev/null | tr -d '/+=' | cut -c1-20; }

START_TS=$(date +%s)

bold "============================================================"
bold "  AuditCore — Production Installer"
bold "============================================================"

# ---------------------------------------------------------------------------
# 1. Prerequisites
# ---------------------------------------------------------------------------
bold "→ Checking prerequisites..."
command -v docker >/dev/null 2>&1 || fail "Docker is not installed. See https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required."
docker info >/dev/null 2>&1 || fail "Docker daemon is not running (try: sudo systemctl start docker)."
command -v openssl >/dev/null 2>&1 || yellow "openssl not found — falling back to /dev/urandom for secrets."

# RAM check (>= 4GB)
if [ -r /proc/meminfo ]; then
  MEM_KB=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
  MEM_GB=$(( MEM_KB / 1024 / 1024 ))
  if [ "$MEM_GB" -lt 4 ]; then
    yellow "⚠ Detected ${MEM_GB}GB RAM (recommended >= 4GB). Continuing anyway."
  else
    green "  RAM: ${MEM_GB}GB OK"
  fi
fi

# Disk check (>= 100GB free on the partition holding this dir)
AVAIL_GB=$(df -BG --output=avail . 2>/dev/null | tail -1 | tr -dc '0-9' || echo 0)
if [ "${AVAIL_GB:-0}" -lt 100 ]; then
  yellow "⚠ Detected ${AVAIL_GB}GB free disk (recommended >= 100GB). Continuing anyway."
else
  green "  Disk: ${AVAIL_GB}GB free OK"
fi
green "  Prerequisites OK"

# ---------------------------------------------------------------------------
# 2. Interactive configuration
# ---------------------------------------------------------------------------
if [ -f .env ]; then
  yellow "⚠ .env already exists. This installer will NOT overwrite it."
  yellow "  Delete .env first to re-run a clean install, or run ./setup.sh to (re)bring-up."
  read -r -p "  Continue using the existing .env? [y/N] " cont
  [ "${cont:-N}" = "y" ] || exit 0
else
  bold "→ Configuration"
  read -r -p "  Company name: " COMPANY_NAME
  [ -n "${COMPANY_NAME:-}" ] || fail "Company name is required."
  read -r -p "  Sector (e.g. تجارة / صناعة / خدمات): " COMPANY_SECTOR
  COMPANY_SECTOR=${COMPANY_SECTOR:-عام}
  read -r -p "  Owner email: " OWNER_EMAIL
  [ -n "${OWNER_EMAIL:-}" ] || fail "Owner email is required."
  read -r -p "  Owner full name: " OWNER_FULL_NAME
  OWNER_FULL_NAME=${OWNER_FULL_NAME:-Owner}

  DEFAULT_PW="$(gen_password)!Aa1"
  read -r -p "  Owner password [auto-generated if blank]: " OWNER_PASSWORD
  OWNER_PASSWORD=${OWNER_PASSWORD:-$DEFAULT_PW}

  bold "→ Supabase connection (Postgres + Auth)"
  yellow "  These come from your Supabase project (Settings → Database / API)."
  read -r -p "  SUPABASE_DB_HOST: " SUPABASE_DB_HOST
  read -r -p "  SUPABASE_DB_USER (e.g. postgres.<ref>): " SUPABASE_DB_USER
  read -r -s -p "  SUPABASE_DB_PASSWORD: " SUPABASE_DB_PASSWORD; echo
  read -r -p "  SUPABASE_URL (https://<ref>.supabase.co): " SUPABASE_URL
  read -r -s -p "  SUPABASE_JWT_SECRET: " SUPABASE_JWT_SECRET; echo
  read -r -s -p "  SUPABASE_SERVICE_ROLE_KEY: " SUPABASE_SERVICE_ROLE_KEY; echo
  read -r -p "  VITE_AUDITCORE_SUPABASE_ANON_KEY: " VITE_ANON

  bold "→ Generating .env with strong secrets..."
  cat > .env <<EOF
# AuditCore .env — generated by install.sh on $(date -u +%FT%TZ)
COMPANY_NAME=${COMPANY_NAME}
COMPANY_SECTOR=${COMPANY_SECTOR}
OWNER_EMAIL=${OWNER_EMAIL}
OWNER_FULL_NAME=${OWNER_FULL_NAME}
OWNER_PASSWORD=${OWNER_PASSWORD}

# Supabase Postgres
SUPABASE_DB_HOST=${SUPABASE_DB_HOST}
SUPABASE_DB_PORT=6543
SUPABASE_DB_NAME=postgres
SUPABASE_DB_USER=${SUPABASE_DB_USER}
SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}

# Supabase Auth
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
SUPABASE_JWT_ALGORITHM=HS256
SUPABASE_JWT_AUDIENCE=authenticated

# Deployment (production: refuse to start on a BYPASSRLS DB role)
ENVIRONMENT=production
ALLOW_RLS_BYPASS=false

# App secrets (auto-generated)
SECRET_KEY=$(gen_secret)
JWT_SECRET=$(gen_secret)
ENCRYPTION_MASTER_KEY=$(gen_secret)
REDIS_PASSWORD=$(gen_secret)
POSTGRES_PASSWORD=$(gen_secret)
# Shared secret authenticating the backend → Baileys WhatsApp bridge.
WHATSAPP_BRIDGE_TOKEN=$(gen_secret)

# Storage / Redis
STORAGE_ROOT=/data
REDIS_URL=redis://redis:6379/0

# Frontend
VITE_AUDITCORE_API_URL=http://localhost:8000
VITE_AUDITCORE_SUPABASE_URL=${SUPABASE_URL}
VITE_AUDITCORE_SUPABASE_ANON_KEY=${VITE_ANON}
EOF
  chmod 600 .env
  green "  .env created (chmod 600)"
fi

# shellcheck disable=SC1091
set -a; source .env; set +a

# ---------------------------------------------------------------------------
# 3. Bring up the stack
# ---------------------------------------------------------------------------
bold "→ Building and starting containers..."
docker compose up -d --build

bold "→ Waiting for backend..."
for _ in $(seq 1 60); do
  if docker compose exec -T backend python -c "print('ok')" >/dev/null 2>&1; then break; fi
  sleep 2
done

# ---------------------------------------------------------------------------
# 4. Migrations + production seed (owner only)
# ---------------------------------------------------------------------------
bold "→ Running migrations..."
docker compose exec -T backend alembic upgrade head

bold "→ Applying RLS policies..."
docker compose exec -T backend python scripts/apply_rls.py

bold "→ Seeding owner account (no demo data)..."
docker compose exec -T \
  -e COMPANY_NAME -e COMPANY_SECTOR -e OWNER_EMAIL -e OWNER_PASSWORD -e OWNER_FULL_NAME \
  backend python scripts/seed_production.py

# ---------------------------------------------------------------------------
# 5. WhatsApp QR + summary
# ---------------------------------------------------------------------------
ELAPSED=$(( ($(date +%s) - START_TS) / 60 ))
green ""
green "============================================================"
green "  AuditCore is LIVE  (install took ~${ELAPSED} min)"
green "============================================================"
green "  Owner login : http://localhost:5173/login"
green "  API docs    : http://localhost:8000/docs"
green "  Health      : http://localhost:8000/health"
green ""
green "  Owner credentials:"
green "    email    : ${OWNER_EMAIL}"
green "    password : ${OWNER_PASSWORD}"
yellow "  ↑ Save these now, then change the password after first login."
green ""
bold  "  WhatsApp setup (one-time):"
green "    1) docker compose logs -f baileys-bridge   # scan the QR shown"
green "       (or open the QR PNG at the bridge's /qr endpoint)"
green "    2) Scan with the Owner's WhatsApp → Linked Devices."
green "    3) Set the owner's number: UPDATE users SET whatsapp_phone='9647...' ..."
green "============================================================"
