from urllib.parse import quote

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    # Supabase Postgres
    SUPABASE_DB_HOST: str
    SUPABASE_DB_PORT: int = 6543
    SUPABASE_DB_NAME: str = "postgres"
    SUPABASE_DB_USER: str
    SUPABASE_DB_PASSWORD: str

    # Supabase Auth (project that issues the JWTs the backend trusts)
    SUPABASE_URL: str = ""
    SUPABASE_JWT_SECRET: str = ""
    SUPABASE_SERVICE_ROLE_KEY: str = ""
    SUPABASE_JWT_ALGORITHM: str = "HS256"
    SUPABASE_JWT_AUDIENCE: str = "authenticated"
    # Anon/publishable key — used by the backend login proxy to call Supabase's
    # password-grant endpoint server-side (so we can rate-limit attempts).
    SUPABASE_ANON_KEY: str = ""

    # Legacy / app crypto (still used for internal signing if needed)
    SECRET_KEY: str = "dev-insecure-secret-change-me"

    REDIS_URL: str = "redis://redis:6379/0"

    # Login rate limiting (Phase 10 hardening): N failures within the window
    # locks that email+IP for LOGIN_LOCKOUT_MINUTES.
    LOGIN_MAX_ATTEMPTS: int = 5
    LOGIN_LOCKOUT_MINUTES: int = 15
    # Idle session timeout enforced in the SPA (minutes).
    SESSION_IDLE_TIMEOUT_MINUTES: int = 15

    # Notifications / WhatsApp (Phase 8)
    BAILEYS_URL: str = "http://baileys-bridge:3001"
    WHATSAPP_QUEUE_KEY: str = "whatsapp:queue"
    # Shared secret sent as X-Bridge-Token to the Baileys bridge. MUST match the
    # bridge's WHATSAPP_BRIDGE_TOKEN; generated by install.sh/setup.sh.
    WHATSAPP_BRIDGE_TOKEN: str = ""
    # Do-Not-Disturb window (Baghdad local hours, 24h). Default 23:00–06:00.
    DND_START_HOUR: int = 23
    DND_END_HOUR: int = 6
    # Default country dialing code prepended to bare local numbers (Iraq = 964).
    DEFAULT_COUNTRY_CODE: str = "964"

    # File storage / encryption (Phase 2)
    STORAGE_ROOT: str = "/data"
    ENCRYPTION_MASTER_KEY: str = "dev-insecure-master-key-change-me"
    MAX_UPLOAD_SIZE: int = 50 * 1024 * 1024

    # CORS — comma-separated exact origins, plus a regex for preview hosts.
    # Example: CORS_ORIGINS="https://app.example.com,https://staging.example.com"
    CORS_ORIGINS: str = "http://localhost:5173,http://localhost:3000"
    # Matches Lovable preview/project domains and localhost by default.
    CORS_ORIGIN_REGEX: str = (
        r"https://([a-z0-9-]+\.)*(lovable\.app|lovableproject\.com|lovable\.dev)"
    )

    @property
    def cors_origins_list(self) -> list[str]:
        return [o.strip() for o in self.CORS_ORIGINS.split(",") if o.strip()]

    @property
    def async_database_url(self) -> str:
        user = quote(self.SUPABASE_DB_USER, safe="")
        pwd = quote(self.SUPABASE_DB_PASSWORD, safe="")
        return (
            f"postgresql+asyncpg://{user}:{pwd}"
            f"@{self.SUPABASE_DB_HOST}:{self.SUPABASE_DB_PORT}/{self.SUPABASE_DB_NAME}"
        )

    @property
    def sync_database_url(self) -> str:
        user = quote(self.SUPABASE_DB_USER, safe="")
        pwd = quote(self.SUPABASE_DB_PASSWORD, safe="")
        return (
            f"postgresql+psycopg2://{user}:{pwd}"
            f"@{self.SUPABASE_DB_HOST}:{self.SUPABASE_DB_PORT}/{self.SUPABASE_DB_NAME}"
        )


settings = Settings()
