/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GmRouteImport } from './routes/gm'
import { Route as AuditorRouteImport } from './routes/auditor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerPerformanceRouteImport } from './routes/owner.performance'
import { Route as OwnerLedgerRouteImport } from './routes/owner.ledger'
import { Route as AuditorUploadRouteImport } from './routes/auditor.upload'
import { Route as AuditorTasksRouteImport } from './routes/auditor.tasks'
import { Route as AuditorCertifyRouteImport } from './routes/auditor.certify'

const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GmRoute = GmRouteImport.update({
  id: '/gm',
  path: '/gm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditorRoute = AuditorRouteImport.update({
  id: '/auditor',
  path: '/auditor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPerformanceRoute = OwnerPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerLedgerRoute = OwnerLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => OwnerRoute,
} as any)
const AuditorUploadRoute = AuditorUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuditorRoute,
} as any)
const AuditorTasksRoute = AuditorTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuditorRoute,
} as any)
const AuditorCertifyRoute = AuditorCertifyRouteImport.update({
  id: '/certify',
  path: '/certify',
  getParentRoute: () => AuditorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditor': typeof AuditorRouteWithChildren
  '/gm': typeof GmRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/owner': typeof OwnerRouteWithChildren
  '/auditor/certify': typeof AuditorCertifyRoute
  '/auditor/tasks': typeof AuditorTasksRoute
  '/auditor/upload': typeof AuditorUploadRoute
  '/owner/ledger': typeof OwnerLedgerRoute
  '/owner/performance': typeof OwnerPerformanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditor': typeof AuditorRouteWithChildren
  '/gm': typeof GmRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/owner': typeof OwnerRouteWithChildren
  '/auditor/certify': typeof AuditorCertifyRoute
  '/auditor/tasks': typeof AuditorTasksRoute
  '/auditor/upload': typeof AuditorUploadRoute
  '/owner/ledger': typeof OwnerLedgerRoute
  '/owner/performance': typeof OwnerPerformanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditor': typeof AuditorRouteWithChildren
  '/gm': typeof GmRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/owner': typeof OwnerRouteWithChildren
  '/auditor/certify': typeof AuditorCertifyRoute
  '/auditor/tasks': typeof AuditorTasksRoute
  '/auditor/upload': typeof AuditorUploadRoute
  '/owner/ledger': typeof OwnerLedgerRoute
  '/owner/performance': typeof OwnerPerformanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditor'
    | '/gm'
    | '/login'
    | '/manager'
    | '/owner'
    | '/auditor/certify'
    | '/auditor/tasks'
    | '/auditor/upload'
    | '/owner/ledger'
    | '/owner/performance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditor'
    | '/gm'
    | '/login'
    | '/manager'
    | '/owner'
    | '/auditor/certify'
    | '/auditor/tasks'
    | '/auditor/upload'
    | '/owner/ledger'
    | '/owner/performance'
  id:
    | '__root__'
    | '/'
    | '/auditor'
    | '/gm'
    | '/login'
    | '/manager'
    | '/owner'
    | '/auditor/certify'
    | '/auditor/tasks'
    | '/auditor/upload'
    | '/owner/ledger'
    | '/owner/performance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditorRoute: typeof AuditorRouteWithChildren
  GmRoute: typeof GmRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  OwnerRoute: typeof OwnerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm': {
      id: '/gm'
      path: '/gm'
      fullPath: '/gm'
      preLoaderRoute: typeof GmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditor': {
      id: '/auditor'
      path: '/auditor'
      fullPath: '/auditor'
      preLoaderRoute: typeof AuditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/performance': {
      id: '/owner/performance'
      path: '/performance'
      fullPath: '/owner/performance'
      preLoaderRoute: typeof OwnerPerformanceRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/ledger': {
      id: '/owner/ledger'
      path: '/ledger'
      fullPath: '/owner/ledger'
      preLoaderRoute: typeof OwnerLedgerRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/auditor/upload': {
      id: '/auditor/upload'
      path: '/upload'
      fullPath: '/auditor/upload'
      preLoaderRoute: typeof AuditorUploadRouteImport
      parentRoute: typeof AuditorRoute
    }
    '/auditor/tasks': {
      id: '/auditor/tasks'
      path: '/tasks'
      fullPath: '/auditor/tasks'
      preLoaderRoute: typeof AuditorTasksRouteImport
      parentRoute: typeof AuditorRoute
    }
    '/auditor/certify': {
      id: '/auditor/certify'
      path: '/certify'
      fullPath: '/auditor/certify'
      preLoaderRoute: typeof AuditorCertifyRouteImport
      parentRoute: typeof AuditorRoute
    }
  }
}

interface AuditorRouteChildren {
  AuditorCertifyRoute: typeof AuditorCertifyRoute
  AuditorTasksRoute: typeof AuditorTasksRoute
  AuditorUploadRoute: typeof AuditorUploadRoute
}

const AuditorRouteChildren: AuditorRouteChildren = {
  AuditorCertifyRoute: AuditorCertifyRoute,
  AuditorTasksRoute: AuditorTasksRoute,
  AuditorUploadRoute: AuditorUploadRoute,
}

const AuditorRouteWithChildren =
  AuditorRoute._addFileChildren(AuditorRouteChildren)

interface OwnerRouteChildren {
  OwnerLedgerRoute: typeof OwnerLedgerRoute
  OwnerPerformanceRoute: typeof OwnerPerformanceRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerLedgerRoute: OwnerLedgerRoute,
  OwnerPerformanceRoute: OwnerPerformanceRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditorRoute: AuditorRouteWithChildren,
  GmRoute: GmRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  OwnerRoute: OwnerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
