/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GmRouteImport } from './routes/gm'
import { Route as AuditorRouteImport } from './routes/auditor'
import { Route as IndexRouteImport } from './routes/index'

const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GmRoute = GmRouteImport.update({
  id: '/gm',
  path: '/gm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditorRoute = AuditorRouteImport.update({
  id: '/auditor',
  path: '/auditor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditor': typeof AuditorRoute
  '/gm': typeof GmRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/owner': typeof OwnerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditor': typeof AuditorRoute
  '/gm': typeof GmRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/owner': typeof OwnerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditor': typeof AuditorRoute
  '/gm': typeof GmRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/owner': typeof OwnerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auditor' | '/gm' | '/login' | '/manager' | '/owner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auditor' | '/gm' | '/login' | '/manager' | '/owner'
  id: '__root__' | '/' | '/auditor' | '/gm' | '/login' | '/manager' | '/owner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditorRoute: typeof AuditorRoute
  GmRoute: typeof GmRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  OwnerRoute: typeof OwnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm': {
      id: '/gm'
      path: '/gm'
      fullPath: '/gm'
      preLoaderRoute: typeof GmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditor': {
      id: '/auditor'
      path: '/auditor'
      fullPath: '/auditor'
      preLoaderRoute: typeof AuditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditorRoute: AuditorRoute,
  GmRoute: GmRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  OwnerRoute: OwnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
